#!/usr/bin/env bash
set -e
cd /var/www/html

echo "Limpando configurações e forçando driver de arquivo..."

# Forçamos o driver de cache para 'file' para evitar que o Laravel tente conectar no MySQL/Postgres antes da hora
/usr/bin/php8.3 artisan config:clear --env=production
/usr/bin/php8.3 artisan cache:clear --env=production

if [ ! -z "$DATABASE_URL" ]; then
    echo "Configurando banco de dados PostgreSQL..."
    # Rodamos a migration garantindo que a conexão seja pgsql
    /usr/bin/php8.3 artisan migrate --force --database=pgsql
fi

echo "Gerando caches de performance..."
/usr/bin/php8.3 artisan config:cache
/usr/bin/php8.3 artisan route:cache
/usr/bin/php8.3 artisan view:cache

echo "Iniciando o Supervisor..."
exec /usr/bin/supervisord -n -c /etc/supervisor/conf.d/supervisord.conf