#!/usr/bin/env bash
set -e
cd /var/www/html

echo "Forçando drivers e porta de produção..."

# Variáveis de ambiente forçadas para garantir consistência
export DB_CONNECTION=pgsql
export DB_PORT=5432
export CACHE_STORE=file
export SESSION_DRIVER=file

echo "Limpando caches..."
/usr/bin/php8.3 artisan config:clear
/usr/bin/php8.3 artisan cache:clear

if [ ! -z "$DATABASE_URL" ]; then
    echo "Configurando banco de dados e populando tabelas (Seed)..."
    # O comando abaixo roda as migrações e, em seguida, os seeders
    /usr/bin/php8.3 artisan migrate --force --seed
fi

echo "Gerando novos caches de performance..."
/usr/bin/php8.3 artisan config:cache
/usr/bin/php8.3 artisan route:cache
/usr/bin/php8.3 artisan view:cache

echo "Iniciando o Supervisor..."
exec /usr/bin/supervisord -n -c /etc/supervisor/conf.d/supervisord.conf